backend:
  name: git-gateway
  repo: mibendiljatiwetan/mibendiljatiwetan
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "konfigurasi"
    label: "Update Konten Website"
    delete: false
    editor:
      preview: false
    files:
      - file: "data.json"
        label: "Database Master Madrasah"
        name: "data"
        fields:
          - label: "Statistik Dashboard (Angka)"
            name: "stats"
            widget: "object"
            fields:
              - {label: "Jumlah Siswa Aktif", name: "siswa", widget: "number"}
              - {label: "Jumlah Guru & Staf", name: "guru", widget: "number"}
              - {label: "Jumlah Ekstrakurikuler", name: "ekskul", widget: "number"}

          - label: "Profil Visi & Misi"
            name: "visiMisi"
            widget: "object"
            fields:
              - {label: "Visi Madrasah", name: "visi", widget: "string"}
              - {label: "Misi Madrasah", name: "misi", widget: "markdown"}
